### ISSUE TITLE
Icons interrupteur absent

### ISSUE THREAD

**Issue by Jeffodilo** [projetsdiy/homy-home-automation-mobile-app#2]
Les interrupteurs On/Off avec des images custom n'ont pas d'icons.
A la place un carré gris avec le logo de l'image absente.

**Comment by cnaslain** [comment]
Vu également avec un import de configuration domoticz. Mon interrupteur est en fait une prise de courant et j'avas mis un logo custom de prise de courant.

Si on reconfigure l'interrupteur avec le logo par défaut dans domoticz (ampoule) et qu'on supprime/réimporte la config dans Homy je n'ai pas trouvé comment rafraîchir la config), on retrouve bien l'ampoule (défaut) dans Homy.
