### ISSUE TITLE
Volets somfy

### ISSUE THREAD

**Issue by albi24** [projetsdiy/homy-home-automation-mobile-app#3]
Les volets somfy ne remontent pas dans l’application.

**Comment by projetsdiy** [comment]
Bonsoir et merci beaucoup pour l’info.

Pourriez-vous m’envoyer les données techniques (tout est expliqué dans cet article en cas de besoin https://projetsdiy.fr/accessoires-compatibles-homy-ou-pas-partagez-votre-experience/) depuis l’application directement pour que je puisse corriger le problème 

Bonnes fêtes de fn d’année

Christophe

**Comment by albi24** [comment]
Bonjour,
Je ne peux pas vous envoyer les infos depuis l’application car les dispositifs ne sont pas présents. Je les ai ajoutés dans la liste « problème ou non compatible avec Domoticz http ».
Merci et bonnes fêtes à vous.
