### ISSUE TITLE
[Jeedom] Volets Fibaro Roller Shutter 3 - Etat non retourné 

### ISSUE THREAD

**Issue by OrpheeGT** [projetsdiy/homy-home-automation-mobile-app#6]
Bonjour,

Tout fonctionne bien à l’exception de l'état retourné par les volets dans Homy alors que dans l'application mobile Jeedom l'état est OK.

Dans Homy l'état est toujours affiché comme full ouvert.

J'utilise Jeedom sur un Synology en conteneur docker avec une clé Aeotec Z-Wave+ Gen 5.

Comment puis-je donner des infos supplémentaires ?

**Comment by projetsdiy** [comment]
Bonjour et merci beaucoup pour le retour

Je travail actuellement sur la prochaine version de Homy. Je vous propose de me re-contacter lorsque la prochaine version sera publiée. Difficile de donner un délai, je suis en train de ré-écrire totalement l’application que l’on pourra à terme utiliser sur box tv et j’espère les montres connectées

Bonne journée

Christophe
