### ISSUE TITLE
[Enhancement] Canevas HTML

### ISSUE THREAD

**Issue by cnaslain** [projetsdiy/homy-home-automation-mobile-app#7]
Imerihome est mort (la société a déposé le bilan) et tout le monde cherche des alternatives à cette appi qui some toutes était pas mal du tout... Une des fonctions que je n'ai pas retrouvé dans Homy et qui était très utile est la possibilité d'ajouter un nouveau module de type canevas HTML pour afficher une page web. Je m'en servais pour afficher un widget météo et/ou des webcams. C'était très utile.

Est-ce que ce genre de module serait possible dans Homy?

**Comment by projetsdiy** [comment]
Oui excellente idée, j'ajoute à la liste des fonctions
