### ISSUE TITLE
[Enhancement] Notion de pages

### ISSUE THREAD

**Issue by cnaslain** [projetsdiy/homy-home-automation-mobile-app#8]
Imerihome est mort (la société a déposé le bilan) et tout le monde cherche des alternatives à cette appi qui some toutes était pas mal du tout... Une des fonctions que je n'ai pas retrouvé dans Homy et qui était très utile est la possibilité d'ajouter des pages en définissant les capteurs/modules que l'on voulait.

Il y a bien les groupes dans Homy mais j'ai pas l'impression que l'on puisse ajouter de nouveaux groupes perso; ça semble être les groupes importés depuis domoticz.

Est-ce que ce genre de module serait possible dans Homy?

**Comment by projetsdiy** [comment]
Bonjour et merci pour votre confiance.
Oui effectivement, Homy fonctionne comme une interface pour Domoticz, donc pas de groupes perso depuis Homy pour le moment.

Je suis en pleine reflexion pour une nouvelle version de Homy simplifiée. La charge de travail est vraiment trop importante pour supporter les évolutions de tous les logiciels domotiques.
